# Generated by Django 4.0.5 on 2022-07-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=10)),
                ('cuerpo', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
            ],
        ),
    ]
