# Generated by Django 4.0.5 on 2022-07-24 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='post',
            new_name='post_usuario',
        ),
    ]
